steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--prod']

  # Step 3: Deploy the application to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
