name: CI/CD Pipeline - Angular Frontend (GitHub Pages)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies (Angular)
      run: |
        npm install

    - name: Build Angular App
      run: |
        npm run build -- --output-path=docs --base-href="/"

    - name: Install gh-pages Action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs

    - name: Set Git identity for deployment
      run: |
        git config --global user.name "PhillipBall1"
        git config --global user.email "pball1346@gmail.com"

    - name: Deploy to GitHub Pages
      run: |
        npx angular-cli-ghpages --dir=docs --no-silent
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
