name: CI/CD Pipeline - Angular Frontend (GitHub Pages)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js 18 or a compatible version for Angular

    - name: Install dependencies (Angular)
      run: |
        npm install

    - name: Build Angular App
      run: |
        npm run build -- --output-path=dist --base-href="/PhillipBall1.github.io/"

    - name: Install angular-cli-ghpages
      run: npm install -g angular-cli-ghpages

    - name: Set Git identity
      run: |
        git config --global user.email "pball1346@gmail.com"
        git config --global user.name "PhillipBall1"

    - name: Set up GitHub token for deployment
      run: |
        git config --global url."https://x-access-token:${{ secrets.GH_TOKEN  }}@github.com".insteadOf "https://github.com"
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN  }}" > ~/.npmrc

    - name: Deploy to GitHub Pages
      run: |
        npx angular-cli-ghpages --dir=dist --branch=gh-pages --no-silent
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
